name: Sketch Art Video Processing

on: [push, pull_request, workflow_dispatch]

jobs:
  process_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Download Input Video
        run: |
          curl -o input.mp4 https://example.com/path-to-your-video.mp4

      - name: Run Sketch Effect Script
        run: python sketch_effect.py

      - name: Upload Processed Video as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-video
          path: output_sketch.mp4

       if __name__ == "__main__":
    input_video = "input.mp4"
    output_video = "output_sketch.mp4"

    import os
    if not os.path.exists(input_video):
        print("ERROR: Input video not found!")
        exit(1)

    process_video(input_video, output_video)

    if os.path.exists(output_video):
        print("SUCCESS: Output video created successfully!")
    else:
        print("ERROR: Output video was not generated.")

        - name: Check Output File
        run: |
          if [ -f "output_sketch.mp4" ]; then
            echo "Output file exists."
          else
            echo "ERROR: No output video found!"
            exit 1
          fi

      - name: Upload Processed Video as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-video
          path: output_sketch.mp4
