name: Sketch Art Video Processing

on: [push, pull_request, workflow_dispatch]

jobs:
  process_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Use Uploaded Video
        run: |
          if [ ! -f "input.mp4" ]; then
            echo "ERROR: input.mp4 not found in the repository!"
            exit 1
          fi

      - name: Run Sketch Effect Script
        run: python sketch_effect.py

      - name: Check Output File
        run: |
          if [ ! -f "output_sketch.mp4" ]; then
            echo "ERROR: No output video found!"
            exit 1
          fi

      - name: Upload Processed Video as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-video
          path: output_sketch.mp4
